project_id = "dyhymmwnfiwlfosaeqfs"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
buckets = []

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_url = "http://127.0.0.1:3000/auth/confirm"

[functions.automated-publishing-api]
verify_jwt = false

[functions.comprehensive-image-validator]
verify_jwt = false

[functions.cron-automation]
verify_jwt = false

[functions.facebook-image-analyzer]
verify_jwt = false

[functions.facebook-setup]
verify_jwt = false

[functions.facebook-webhook-v2]
verify_jwt = false

[functions.facebook-webhook]
verify_jwt = false

[functions.fix-cron-urls]
verify_jwt = false

[functions.fix-specific-cron]
verify_jwt = false

[functions.gemini-content-quality-check]
verify_jwt = false

[functions.gemini-image-analysis]
verify_jwt = false

[functions.gemini-image-edit-prompt]
verify_jwt = false

[functions.gemini-image-editing]
verify_jwt = false

[functions.gemini-image-generation]
verify_jwt = false

[functions.gemini-interactive-questions]
verify_jwt = false

[functions.gemini-logo-analysis]
verify_jwt = false

[functions.gemini-marketing-content]
verify_jwt = false

[functions.gemini-proxy]
verify_jwt = false

[functions.gemini-suggestions]
verify_jwt = false

[functions.gemini-text-extractor]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.get-pixabay-key]
verify_jwt = false

[functions.google-oauth]
verify_jwt = false

[functions.prompt-analyzer]
verify_jwt = false

[functions.structured-prompt-generator]
verify_jwt = false

[functions.test-cron-automation]
verify_jwt = false