// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyhymmwnfiwlfosaeqfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5aHltbXduZml3bGZvc2FlcWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTE3NTUsImV4cCI6MjA3MTE2Nzc1NX0.EbKd_rK6RJWj1r1yvwYyrOam9K4TKsquSX4IVAXTXiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});