// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsmxvgerbngmmkxncovg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzbXh2Z2VyYm5nbW1reG5jb3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMDUxNTIsImV4cCI6MjA3MDg4MTE1Mn0.r0TBsa_ztoMdf9rGsQGp8TJlAaJDu5ZOJZkgyZh2SSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});